### ISSUE TITLE
websocket routing question

### ISSUE THREAD

**Issue by csakis** [mwambler/xockets.io#11]
As far as I understand, I can route the messages by uri multiple ways.
For example /app.nsf* will send the message to all the users who are logged into app.nsf and could be on any of the xpages.

Is it possible to route to somebody who is logged into an application and could be on any of the xpages but the uri ends with for example with a DocUNID. For example I want to send messages to these users by uris:
```
/app.nsf/home.xsp/DocUNID
/app.nsf/page.xsp/DocUNID
```
I cannot use /app.nsf*/DocUNID, right?
When I look at the source I can see that the recipient filtering is done with StartsWith ?
Could it be done with for example regular expression?

**Comment by mwambler** [comment]
Since it seems the UNID is the key element for your routing path, have you tried manipulating the websocket url and setting it to something like "/app.nsf/DocUNID"?  You can create the custom url via the below call:

websocketBean.getCustomWebSocketUrl(HttpServletRequest req, String sessionId, String **sourceUri**);


Note, allowing regex expressions to be input from external sources (e.g. to field in SocketMessage) opens xockets.io up to some DoS attacks (see link below).

https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS

**Comment by csakis** [comment]
I managed to modify the webSocketUrl from client side JavaScript, but I will try the method above, that looks simpler. I understand about the regex problem.

**Comment by csakis** [comment]
Could you please give an example how to use the 
`websocketBean.getCustomWebSocketUrl(HttpServletRequest req, String sessionId, String sourceUri);`
function?

**Comment by mrmiggles** [comment]
I think this is the first parameter is:
 var externalContext = facesContext.getExternalContext(); 
var request = externalContext.getRequest();

and the second parameter is:
var URI = externalContext.getRequest().getRequestURI()

**Comment by csakis** [comment]
That did not work, it's missing the websocket Id from the end of the uri
It looks like this now:
wss://dominoserver.com:8443/websocket/application.nsf/XPage.xsp/DocUNID.

**Comment by mwambler** [comment]
Below creates / overrides uri for the user to /yabadabadoo.  Output looks like:

wss://tekcounsel.net:443/websocket/yabadabadooo/69A6C22BC1BB4D81974313DD4DBCF557AE24BEF4


````javascript
var req = facesContext.getExternalContext().getRequest();
var sessionId = req.getSession().getId();
var uri = "/yabadabadooo";

return websocketBean.getCustomWebSocketUrl(req,sessionId,uri);
````

**Comment by csakis** [comment]
Indeed Mark, that works. Probably it's best to add the application.nsf after /websocket/.
