### ISSUE TITLE
Server with two network cards with xockets

### ISSUE THREAD

**Issue by mrmiggles** [mwambler/xockets.io#28]
Looking at the code, if I understand correctly I can feasibly have a server with two network cards and have websockets listen on one card with one IP on port 443 and the domino server itself listen on the other card on a different ip on port 443, correct? I would just need to set the allowed origins to be from the network card with the IP listening for wss requests? This would alleviate the need for two ports but necessitate the need for two IP but those might be easier to come by vs poking open a different port in my case

**Comment by csakis** [comment]
You might not even need two real ips, if the two network cards could speak
to each other internally. The servers on the high side come with 4-8
network cards.

The problem on the high side would be coming up with new real ips,
apparently


On October 26, 2016 at 10:06:31 PM, Miguel (notifications@github.com) wrote:

Looking at the code, if I understand correctly I can feasibly have a server
with two network cards and have websockets listen on one card with one IP
on port 443 and the domino server itself listen on the other card on a
different ip, correct? I would just need to set the allowed origins to be
from the network card with the IP listening for wss requests? This would
alleviate the need for two ports but necessitate the need for two IP but
those might be easier to come by vs poking open a different port in my case

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mwambler/xockets.io/issues/28>, or mute the thread

**Comment by mrmiggles** [comment]
Might need to start a new thread for this but instead of all mentioned above, when we use the SSLContextBuilder we set ClientAuth to true. Then we can set the TrustMangerFactory to use our Keystore that we create in the websocket set up process
