### ISSUE TITLE
Feature Pack 8 Designer problems

### ISSUE THREAD

**Issue by csakis** [mwambler/xockets.io#37]
I tried to install the xockets 3.0.2 into Designer and got problems.
![image](https://cloud.githubusercontent.com/assets/2583367/23809079/7808e392-0589-11e7-88ce-fff7b1b36450.png)

I tried to install OpenNTF Extension Library and that did not help either. I am not able to build my application now.
![image](https://cloud.githubusercontent.com/assets/2583367/23809124/a9e5bda4-0589-11e7-9401-1d1aafcfc7dc.png)

The server side plugin seems to work just fine and I did not install the OpenNTF extension library on the server, since FP8 contains it already.

**Comment by csakis** [comment]
This problems is something local, nothing to do with the github repo.

**Comment by mrmiggles** [comment]
Actually, I think Csaba was correct on this one. I had to add in some sources from the extension library and re-build xockets so it didn't depend on the extension library being installed in Designer. xockets.io was searching for these plugins:

_com.ibm.domino.das
com.ibm.domino.commons
_com.ibm.domino.services__

After I added those plugins to the xockets project and re-built I was able to build the projects in Designer once more without the extension library and with FP8 installed. I wasn't able to find IBM's equivalent of com.ibm.domino.das (if they even included one in FP8), which is why I couldn't just exchange the library in the xockets src and re-build. I'm sure you'll find a more clever way of solving this.

I, however, ran into problems when I changed the minimum support release to 9.0.1FP8. Application wouldn't run.
